(function($){$.fn.hoverIntent=function(handlerIn,handlerOut,selector){var cfg={interval:100,sensitivity:6,timeout:0};if(typeof handlerIn==="object"){cfg=$.extend(cfg,handlerIn)}else{if($.isFunction(handlerOut)){cfg=$.extend(cfg,{over:handlerIn,out:handlerOut,selector:selector})}else{cfg=$.extend(cfg,{over:handlerIn,out:handlerIn,selector:handlerOut})}}var cX,cY,pX,pY;var track=function(ev){cX=ev.pageX;cY=ev.pageY};var compare=function(ev,ob){ob.hoverIntent_t=clearTimeout(ob.hoverIntent_t);if(Math.sqrt((pX-cX)*(pX-cX)+(pY-cY)*(pY-cY))<cfg.sensitivity){$(ob).off("mousemove.hoverIntent",track);ob.hoverIntent_s=true;return cfg.over.apply(ob,[ev])}else{pX=cX;pY=cY;ob.hoverIntent_t=setTimeout(function(){compare(ev,ob)},cfg.interval)}};var delay=function(ev,ob){ob.hoverIntent_t=clearTimeout(ob.hoverIntent_t);ob.hoverIntent_s=false;return cfg.out.apply(ob,[ev])};var handleHover=function(e){var ev=$.extend({},e);var ob=this;if(ob.hoverIntent_t){ob.hoverIntent_t=clearTimeout(ob.hoverIntent_t)}if(e.type==="mouseenter"){pX=ev.pageX;pY=ev.pageY;$(ob).on("mousemove.hoverIntent",track);if(!ob.hoverIntent_s){ob.hoverIntent_t=setTimeout(function(){compare(ev,ob)},cfg.interval)}}else{$(ob).off("mousemove.hoverIntent",track);if(ob.hoverIntent_s){ob.hoverIntent_t=setTimeout(function(){delay(ev,ob)},cfg.timeout)}}};return this.on({"mouseenter.hoverIntent":handleHover,"mouseleave.hoverIntent":handleHover},cfg.selector)}})(jQuery);

cards = {
"Ancestral Healing" : "https://s3.amazonaws.com/tempostorm/Ancestral_Healing.png",
"Ancient Secrets" : "https://s3.amazonaws.com/tempostorm/Ancient_Secrets.png",
"Ancient Teachings" : "https://s3.amazonaws.com/tempostorm/Ancient_Teachings.png",
"Avatar of the Coin" : "https://s3.amazonaws.com/tempostorm/Avatar_of_the_Coin.png",
"Backstab" : "https://s3.amazonaws.com/tempostorm/Backstab.png",
"Barrel" : "https://s3.amazonaws.com/tempostorm/Barrel.png",
"Bear Form" : "https://s3.amazonaws.com/tempostorm/Bear_Form.png",
"Become Hogger" : "https://s3.amazonaws.com/tempostorm/Become_Hogger.png",
"Bounce" : "https://s3.amazonaws.com/tempostorm/Bounce.png",
"Break Weapon" : "https://s3.amazonaws.com/tempostorm/Break_Weapon.png",
"Cat Form" : "https://s3.amazonaws.com/tempostorm/Cat_Form.png",
"Chicken" : "https://s3.amazonaws.com/tempostorm/Chicken.png",
"Circle of Healing" : "https://s3.amazonaws.com/tempostorm/Circle_of_Healing.png",
"Consume" : "https://s3.amazonaws.com/tempostorm/Consume.png",
"Crash" : "https://s3.amazonaws.com/tempostorm/Crash.png",
"Damage 1" : "https://s3.amazonaws.com/tempostorm/Damage_1.png",
"Damage 5" : "https://s3.amazonaws.com/tempostorm/Damage_5.png",
"Damage all but 1" : "https://s3.amazonaws.com/tempostorm/Damage_all_but_1.png",
"Damage Reflector" : "https://s3.amazonaws.com/tempostorm/Damage_Reflector.png",
"Darkness Calls" : "https://s3.amazonaws.com/tempostorm/Darkness_Calls.png",
"Demigod's Favor" : "https://s3.amazonaws.com/tempostorm/Demigod's_Favor.png",
"Destory Hero Power" : "https://s3.amazonaws.com/tempostorm/Destory_Hero_Power.png",
"Destroy" : "https://s3.amazonaws.com/tempostorm/Destroy.png",
"Destroy All Heroes" : "https://s3.amazonaws.com/tempostorm/Destroy_All_Heroes.png",
"Destroy All Minions" : "https://s3.amazonaws.com/tempostorm/Destroy_All_Minions.png",
"Discard" : "https://s3.amazonaws.com/tempostorm/Discard.png",
"Dispel" : "https://s3.amazonaws.com/tempostorm/Dispel.png",
"Do Nothing" : "https://s3.amazonaws.com/tempostorm/Do_Nothing.png",
"Draw 3 Cards" : "https://s3.amazonaws.com/tempostorm/Draw_3_Cards.png",
"Dream" : "https://s3.amazonaws.com/tempostorm/Dream.png",
"Enable Emotes" : "https://s3.amazonaws.com/tempostorm/Enable_Emotes.png",
"Enable for Attack" : "https://s3.amazonaws.com/tempostorm/Enable_for_Attack.png",
"Enchant" : "https://s3.amazonaws.com/tempostorm/Enchant.png",
"Excess Mana" : "https://s3.amazonaws.com/tempostorm/Excess_Mana.png",
"Free Cards" : "https://s3.amazonaws.com/tempostorm/Free_Cards.png",
"Freeze" : "https://s3.amazonaws.com/tempostorm/Freeze.png",
"Frog" : "https://s3.amazonaws.com/tempostorm/Frog.png",
"Hand Swapper Minion" : "https://s3.amazonaws.com/tempostorm/Hand_Swapper_Minion.png",
"Hand to Deck" : "https://s3.amazonaws.com/tempostorm/Hand_to_Deck.png",
"Hunter's Mark" : "https://s3.amazonaws.com/tempostorm/Hunter's_Mark.png",
"Inner Rage" : "https://s3.amazonaws.com/tempostorm/Inner_Rage.png",
"Innervate" : "https://s3.amazonaws.com/tempostorm/Innervate.png",
"Leader of the Pack" : "https://s3.amazonaws.com/tempostorm/Leader_of_the_Pack.png",
"Mill 10" : "https://s3.amazonaws.com/tempostorm/Mill_10.png",
"Mill 30" : "https://s3.amazonaws.com/tempostorm/Mill_30.png",
"Molasses" : "https://s3.amazonaws.com/tempostorm/Molasses.png",
"Moonfire" : "https://s3.amazonaws.com/tempostorm/Moonfire.png",
"Murloc Scout" : "https://s3.amazonaws.com/tempostorm/Murloc_Scout.png",
"Necrotic Aura" : "https://s3.amazonaws.com/tempostorm/Necrotic_Aura.png",
"Nightmare" : "https://s3.amazonaws.com/tempostorm/Nightmare.png",
"Opponent Concede" : "https://s3.amazonaws.com/tempostorm/Opponent_Concede.png",
"Opponent Disconnect" : "https://s3.amazonaws.com/tempostorm/Opponent_Disconnect.png",
"Power of the Ziggurat" : "https://s3.amazonaws.com/tempostorm/Power_of_the_Ziggurat.png",
"Preparation" : "https://s3.amazonaws.com/tempostorm/Preparation.png",
"Restore 1" : "https://s3.amazonaws.com/tempostorm/Restore_1.png",
"Restore 5" : "https://s3.amazonaws.com/tempostorm/Restore_5.png",
"Restore All Health" : "https://s3.amazonaws.com/tempostorm/Restore_All_Health.png",
"Reveal Hand" : "https://s3.amazonaws.com/tempostorm/Reveal_Hand.png",
"Rooted" : "https://s3.amazonaws.com/tempostorm/Rooted.png",
"Sacrificial Pact" : "https://s3.amazonaws.com/tempostorm/Sacrificial_Pact.png",
"Server Crash" : "https://s3.amazonaws.com/tempostorm/Server_Crash.png",
"Shadow of Nothing" : "https://s3.amazonaws.com/tempostorm/Shadow_of_Nothing.png",
"Shadowstep" : "https://s3.amazonaws.com/tempostorm/Shadowstep.png",
"Shan'do's Lesson" : "https://s3.amazonaws.com/tempostorm/Shan'do's_Lesson.png",
"Sheep" : "https://s3.amazonaws.com/tempostorm/Sheep.png",
"Silence" : "https://s3.amazonaws.com/tempostorm/Silence.png",
"Silence - debug" : "https://s3.amazonaws.com/tempostorm/Silence_-_debug.png",
"Snake" : "https://s3.amazonaws.com/tempostorm/Snake.png",
"Snake Ball" : "https://s3.amazonaws.com/tempostorm/Snake_Ball.png",
"Soulfire" : "https://s3.amazonaws.com/tempostorm/Soulfire.png",
"Steal Card" : "https://s3.amazonaws.com/tempostorm/Steal_Card.png",
"Summon a Panther" : "https://s3.amazonaws.com/tempostorm/Summon_a_Panther.png",
"Summon a random Secret" : "https://s3.amazonaws.com/tempostorm/Summon_a_random_Secret.png",
"The Coin" : "https://s3.amazonaws.com/tempostorm/The_Coin.png",
"Totemic Might" : "https://s3.amazonaws.com/tempostorm/Totemic_Might.png",
"Uproot" : "https://s3.amazonaws.com/tempostorm/Uproot.png",
"Vengeance" : "https://s3.amazonaws.com/tempostorm/Vengeance.png",
"Violet Apprentice" : "https://s3.amazonaws.com/tempostorm/Violet_Apprentice.png",
"Wisp" : "https://s3.amazonaws.com/tempostorm/Wisp.png",
"Abusive Sergeant" : "https://s3.amazonaws.com/tempostorm/Abusive_Sergeant.png",
"Andy Brock" : "https://s3.amazonaws.com/tempostorm/Andy_Brock.png",
"Angry Chicken" : "https://s3.amazonaws.com/tempostorm/Angry_Chicken.png",
"Arcane Missiles" : "https://s3.amazonaws.com/tempostorm/Arcane_Missiles.png",
"Arcane Shot" : "https://s3.amazonaws.com/tempostorm/Arcane_Shot.png",
"Argent Squire" : "https://s3.amazonaws.com/tempostorm/Argent_Squire.png",
"Avenge" : "https://s3.amazonaws.com/tempostorm/Avenge.png",
"Bananas" : "https://s3.amazonaws.com/tempostorm/Bananas.png",
"Barrel Toss" : "https://s3.amazonaws.com/tempostorm/Barrel_Toss.png",
"Bestial Wrath" : "https://s3.amazonaws.com/tempostorm/Bestial_Wrath.png",
"Blessing of Might" : "https://s3.amazonaws.com/tempostorm/Blessing_of_Might.png",
"Blessing of Wisdom" : "https://s3.amazonaws.com/tempostorm/Blessing_of_Wisdom.png",
"Blood Imp" : "https://s3.amazonaws.com/tempostorm/Blood_Imp.png",
"Bloodsail Corsair" : "https://s3.amazonaws.com/tempostorm/Bloodsail_Corsair.png",
"Boar" : "https://s3.amazonaws.com/tempostorm/Boar.png",
"Claw" : "https://s3.amazonaws.com/tempostorm/Claw.png",
"Cold Blood" : "https://s3.amazonaws.com/tempostorm/Cold_Blood.png",
"Conceal" : "https://s3.amazonaws.com/tempostorm/Conceal.png",
"Corruption" : "https://s3.amazonaws.com/tempostorm/Corruption.png",
"Crazed Hunter" : "https://s3.amazonaws.com/tempostorm/Crazed_Hunter.png",
"Crazy Monkey" : "https://s3.amazonaws.com/tempostorm/Crazy_Monkey.png",
"Damaged Golem" : "https://s3.amazonaws.com/tempostorm/Damaged_Golem.png",
"Deadly Poison" : "https://s3.amazonaws.com/tempostorm/Deadly_Poison.png",
"Deathcharger" : "https://s3.amazonaws.com/tempostorm/Deathcharger.png",
"Defender" : "https://s3.amazonaws.com/tempostorm/Defender.png",
"Defias Bandit" : "https://s3.amazonaws.com/tempostorm/Defias_Bandit.png",
"Derek Sakamoto" : "https://s3.amazonaws.com/tempostorm/Derek_Sakamoto.png",
"Dust Devil" : "https://s3.amazonaws.com/tempostorm/Dust_Devil.png",
"Earth Shock" : "https://s3.amazonaws.com/tempostorm/Earth_Shock.png",
"Elven Archer" : "https://s3.amazonaws.com/tempostorm/Elven_Archer.png",
"Emboldener 3000" : "https://s3.amazonaws.com/tempostorm/Emboldener_3000.png",
"Execute" : "https://s3.amazonaws.com/tempostorm/Execute.png",
"Eye for an Eye" : "https://s3.amazonaws.com/tempostorm/Eye_for_an_Eye.png",
"Flame Imp" : "https://s3.amazonaws.com/tempostorm/Flame_Imp.png",
"Flame of Azzinoth" : "https://s3.amazonaws.com/tempostorm/Flame_of_Azzinoth.png",
"Flare" : "https://s3.amazonaws.com/tempostorm/Flare.png",
"Forked Lightning" : "https://s3.amazonaws.com/tempostorm/Forked_Lightning.png",
"Frost Shock" : "https://s3.amazonaws.com/tempostorm/Frost_Shock.png",
"Goldshire Footman" : "https://s3.amazonaws.com/tempostorm/Goldshire_Footman.png",
"Grimscale Oracle" : "https://s3.amazonaws.com/tempostorm/Grimscale_Oracle.png",
"Hand of Protection" : "https://s3.amazonaws.com/tempostorm/Hand_of_Protection.png",
"Healing Totem" : "https://s3.amazonaws.com/tempostorm/Healing_Totem.png",
"Holy Smite" : "https://s3.amazonaws.com/tempostorm/Holy_Smite.png",
"Homing Chicken" : "https://s3.amazonaws.com/tempostorm/Homing_Chicken.png",
"Hound" : "https://s3.amazonaws.com/tempostorm/Hound.png",
"Humility" : "https://s3.amazonaws.com/tempostorm/Humility.png",
"Hungry Crab" : "https://s3.amazonaws.com/tempostorm/Hungry_Crab.png",
"Ice Lance" : "https://s3.amazonaws.com/tempostorm/Ice_Lance.png",
"Imp" : "https://s3.amazonaws.com/tempostorm/Imp.png",
"Inner Fire" : "https://s3.amazonaws.com/tempostorm/Inner_Fire.png",
"Leper Gnome" : "https://s3.amazonaws.com/tempostorm/Leper_Gnome.png",
"Light's Justice" : "https://s3.amazonaws.com/tempostorm/Light's_Justice.png",
"Lightning Bolt" : "https://s3.amazonaws.com/tempostorm/Lightning_Bolt.png",
"Lightwarden" : "https://s3.amazonaws.com/tempostorm/Lightwarden.png",
"Mana Wyrm" : "https://s3.amazonaws.com/tempostorm/Mana_Wyrm.png",
"Mechanical Dragonling" : "https://s3.amazonaws.com/tempostorm/Mechanical_Dragonling.png",
"Mind Vision" : "https://s3.amazonaws.com/tempostorm/Mind_Vision.png",
"Mirror Image" : "https://s3.amazonaws.com/tempostorm/Mirror_Image.png",
"Mortal Coil" : "https://s3.amazonaws.com/tempostorm/Mortal_Coil.png",
"Murloc" : "https://s3.amazonaws.com/tempostorm/Murloc.png",
"Murloc Raider" : "https://s3.amazonaws.com/tempostorm/Murloc_Raider.png",
"Murloc Tidecaller" : "https://s3.amazonaws.com/tempostorm/Murloc_Tidecaller.png",
"Naga Myrmidon" : "https://s3.amazonaws.com/tempostorm/Naga_Myrmidon.png",
"Naturalize" : "https://s3.amazonaws.com/tempostorm/Naturalize.png",
"Noble Sacrifice" : "https://s3.amazonaws.com/tempostorm/Noble_Sacrifice.png",
"Northshire Cleric" : "https://s3.amazonaws.com/tempostorm/Northshire_Cleric.png",
"Pandaren Scout" : "https://s3.amazonaws.com/tempostorm/Pandaren_Scout.png",
"Poultryizer" : "https://s3.amazonaws.com/tempostorm/Poultryizer.png",
"Power Overwhelming" : "https://s3.amazonaws.com/tempostorm/Power_Overwhelming.png",
"Power Word: Shield" : "https://s3.amazonaws.com/tempostorm/Power_Word%3A_Shield.png",
"Redemption" : "https://s3.amazonaws.com/tempostorm/Redemption.png",
"Repair Bot" : "https://s3.amazonaws.com/tempostorm/Repair_Bot.png",
"Repentance" : "https://s3.amazonaws.com/tempostorm/Repentance.png",
"Riverpaw Gnoll" : "https://s3.amazonaws.com/tempostorm/Riverpaw_Gnoll.png",
"Rockbiter Weapon" : "https://s3.amazonaws.com/tempostorm/Rockbiter_Weapon.png",
"Savagery" : "https://s3.amazonaws.com/tempostorm/Savagery.png",
"Searing Totem" : "https://s3.amazonaws.com/tempostorm/Searing_Totem.png",
"Secretkeeper" : "https://s3.amazonaws.com/tempostorm/Secretkeeper.png",
"Shield Slam" : "https://s3.amazonaws.com/tempostorm/Shield_Slam.png",
"Shieldbearer" : "https://s3.amazonaws.com/tempostorm/Shieldbearer.png",
"Silver Hand Recruit" : "https://s3.amazonaws.com/tempostorm/Silver_Hand_Recruit.png",
"Sinister Strike" : "https://s3.amazonaws.com/tempostorm/Sinister_Strike.png",
"Skeleton" : "https://s3.amazonaws.com/tempostorm/Skeleton.png",
"Slime" : "https://s3.amazonaws.com/tempostorm/Slime.png",
"Southsea Deckhand" : "https://s3.amazonaws.com/tempostorm/Southsea_Deckhand.png",
"Spectral Spider" : "https://s3.amazonaws.com/tempostorm/Spectral_Spider.png",
"Squire" : "https://s3.amazonaws.com/tempostorm/Squire.png",
"Squirrel" : "https://s3.amazonaws.com/tempostorm/Squirrel.png",
"Steven Gabriel" : "https://s3.amazonaws.com/tempostorm/Steven_Gabriel.png",
"Stoneclaw Totem" : "https://s3.amazonaws.com/tempostorm/Stoneclaw_Totem.png",
"Stonetusk Boar" : "https://s3.amazonaws.com/tempostorm/Stonetusk_Boar.png",
"Timber Wolf" : "https://s3.amazonaws.com/tempostorm/Timber_Wolf.png",
"Tracking" : "https://s3.amazonaws.com/tempostorm/Tracking.png",
"Transcendence" : "https://s3.amazonaws.com/tempostorm/Transcendence.png",
"Treant" : "https://s3.amazonaws.com/tempostorm/Treant.png",
"Undertaker" : "https://s3.amazonaws.com/tempostorm/Undertaker.png",
"Upgrade!" : "https://s3.amazonaws.com/tempostorm/Upgrade!.png",
"Voidwalker" : "https://s3.amazonaws.com/tempostorm/Voidwalker.png",
"Voodoo Doctor" : "https://s3.amazonaws.com/tempostorm/Voodoo_Doctor.png",
"Webspinner" : "https://s3.amazonaws.com/tempostorm/Webspinner.png",
"Whelp" : "https://s3.amazonaws.com/tempostorm/Whelp.png",
"Whirlwind" : "https://s3.amazonaws.com/tempostorm/Whirlwind.png",
"Worgen Infiltrator" : "https://s3.amazonaws.com/tempostorm/Worgen_Infiltrator.png",
"Worthless Imp" : "https://s3.amazonaws.com/tempostorm/Worthless_Imp.png",
"Wrath of Air Totem" : "https://s3.amazonaws.com/tempostorm/Wrath_of_Air_Totem.png",
"Young Dragonhawk" : "https://s3.amazonaws.com/tempostorm/Young_Dragonhawk.png",
"Young Priestess" : "https://s3.amazonaws.com/tempostorm/Young_Priestess.png",
"Zombie Chow" : "https://s3.amazonaws.com/tempostorm/Zombie_Chow.png",
"Acidic Swamp Ooze" : "https://s3.amazonaws.com/tempostorm/Acidic_Swamp_Ooze.png",
"Amani Berserker" : "https://s3.amazonaws.com/tempostorm/Amani_Berserker.png",
"Ancestral Spirit" : "https://s3.amazonaws.com/tempostorm/Ancestral_Spirit.png",
"Ancient Watcher" : "https://s3.amazonaws.com/tempostorm/Ancient_Watcher.png",
"Arcane Explosion" : "https://s3.amazonaws.com/tempostorm/Arcane_Explosion.png",
"Argent Protector" : "https://s3.amazonaws.com/tempostorm/Argent_Protector.png",
"Armorsmith" : "https://s3.amazonaws.com/tempostorm/Armorsmith.png",
"Battle Rage" : "https://s3.amazonaws.com/tempostorm/Battle_Rage.png",
"Betrayal" : "https://s3.amazonaws.com/tempostorm/Betrayal.png",
"Blade Flurry" : "https://s3.amazonaws.com/tempostorm/Blade_Flurry.png",
"Bloodfen Raptor" : "https://s3.amazonaws.com/tempostorm/Bloodfen_Raptor.png",
"Bloodmage Thalnos" : "https://s3.amazonaws.com/tempostorm/Bloodmage_Thalnos.png",
"Bloodsail Raider" : "https://s3.amazonaws.com/tempostorm/Bloodsail_Raider.png",
"Bluegill Warrior" : "https://s3.amazonaws.com/tempostorm/Bluegill_Warrior.png",
"Captain's Parrot" : "https://s3.amazonaws.com/tempostorm/Captain's_Parrot.png",
"Cleave" : "https://s3.amazonaws.com/tempostorm/Cleave.png",
"Commanding Shout" : "https://s3.amazonaws.com/tempostorm/Commanding_Shout.png",
"Crazed Alchemist" : "https://s3.amazonaws.com/tempostorm/Crazed_Alchemist.png",
"Cruel Taskmaster" : "https://s3.amazonaws.com/tempostorm/Cruel_Taskmaster.png",
"Defias Ringleader" : "https://s3.amazonaws.com/tempostorm/Defias_Ringleader.png",
"Demonfire" : "https://s3.amazonaws.com/tempostorm/Demonfire.png",
"Dire Wolf Alpha" : "https://s3.amazonaws.com/tempostorm/Dire_Wolf_Alpha.png",
"Divine Spirit" : "https://s3.amazonaws.com/tempostorm/Divine_Spirit.png",
"Doomsayer" : "https://s3.amazonaws.com/tempostorm/Doomsayer.png",
"Echoing Ooze" : "https://s3.amazonaws.com/tempostorm/Echoing_Ooze.png",
"Equality" : "https://s3.amazonaws.com/tempostorm/Equality.png",
"Eviscerate" : "https://s3.amazonaws.com/tempostorm/Eviscerate.png",
"Explosive Trap" : "https://s3.amazonaws.com/tempostorm/Explosive_Trap.png",
"Faerie Dragon" : "https://s3.amazonaws.com/tempostorm/Faerie_Dragon.png",
"Fiery War Axe" : "https://s3.amazonaws.com/tempostorm/Fiery_War_Axe.png",
"Finkle Einhorn" : "https://s3.amazonaws.com/tempostorm/Finkle_Einhorn.png",
"Flametongue Totem" : "https://s3.amazonaws.com/tempostorm/Flametongue_Totem.png",
"Freezing Trap" : "https://s3.amazonaws.com/tempostorm/Freezing_Trap.png",
"Frostbolt" : "https://s3.amazonaws.com/tempostorm/Frostbolt.png",
"Frostwolf Grunt" : "https://s3.amazonaws.com/tempostorm/Frostwolf_Grunt.png",
"Gnoll" : "https://s3.amazonaws.com/tempostorm/Gnoll.png",
"Haunted Creeper" : "https://s3.amazonaws.com/tempostorm/Haunted_Creeper.png",
"Heroic Strike" : "https://s3.amazonaws.com/tempostorm/Heroic_Strike.png",
"Hidden Gnome" : "https://s3.amazonaws.com/tempostorm/Hidden_Gnome.png",
"Holy Light" : "https://s3.amazonaws.com/tempostorm/Holy_Light.png",
"Hyena" : "https://s3.amazonaws.com/tempostorm/Hyena.png",
"Ironbeak Owl" : "https://s3.amazonaws.com/tempostorm/Ironbeak_Owl.png",
"Knife Juggler" : "https://s3.amazonaws.com/tempostorm/Knife_Juggler.png",
"Kobold Geomancer" : "https://s3.amazonaws.com/tempostorm/Kobold_Geomancer.png",
"Lightwell" : "https://s3.amazonaws.com/tempostorm/Lightwell.png",
"Loot Hoarder" : "https://s3.amazonaws.com/tempostorm/Loot_Hoarder.png",
"Lorewalker Cho" : "https://s3.amazonaws.com/tempostorm/Lorewalker_Cho.png",
"Mad Bomber" : "https://s3.amazonaws.com/tempostorm/Mad_Bomber.png",
"Mad Scientist" : "https://s3.amazonaws.com/tempostorm/Mad_Scientist.png",
"Mana Addict" : "https://s3.amazonaws.com/tempostorm/Mana_Addict.png",
"Mana Wraith" : "https://s3.amazonaws.com/tempostorm/Mana_Wraith.png",
"Mark of the Wild" : "https://s3.amazonaws.com/tempostorm/Mark_of_the_Wild.png",
"Master Swordsmith" : "https://s3.amazonaws.com/tempostorm/Master_Swordsmith.png",
"Michael Schweitzer" : "https://s3.amazonaws.com/tempostorm/Michael_Schweitzer.png",
"Millhouse Manastorm" : "https://s3.amazonaws.com/tempostorm/Millhouse_Manastorm.png",
"Mind Blast" : "https://s3.amazonaws.com/tempostorm/Mind_Blast.png",
"Misdirection" : "https://s3.amazonaws.com/tempostorm/Misdirection.png",
"Murloc Tidehunter" : "https://s3.amazonaws.com/tempostorm/Murloc_Tidehunter.png",
"Nat Pagle" : "https://s3.amazonaws.com/tempostorm/Nat_Pagle.png",
"Nerub'ar Weblord" : "https://s3.amazonaws.com/tempostorm/Nerub'ar_Weblord.png",
"Nerubian Egg" : "https://s3.amazonaws.com/tempostorm/Nerubian_Egg.png",
"NOOOOOOOOOOOO" : "https://s3.amazonaws.com/tempostorm/NOOOOOOOOOOOO.png",
"Novice Engineer" : "https://s3.amazonaws.com/tempostorm/Novice_Engineer.png",
"Panther" : "https://s3.amazonaws.com/tempostorm/Panther.png",
"Patient Assassin" : "https://s3.amazonaws.com/tempostorm/Patient_Assassin.png",
"Pint-Sized Summoner" : "https://s3.amazonaws.com/tempostorm/Pint-Sized_Summoner.png",
"Power of the Wild" : "https://s3.amazonaws.com/tempostorm/Power_of_the_Wild.png",
"Rachelle Davis" : "https://s3.amazonaws.com/tempostorm/Rachelle_Davis.png",
"Rampage" : "https://s3.amazonaws.com/tempostorm/Rampage.png",
"Reincarnate" : "https://s3.amazonaws.com/tempostorm/Reincarnate.png",
"River Crocolisk" : "https://s3.amazonaws.com/tempostorm/River_Crocolisk.png",
"Sap" : "https://s3.amazonaws.com/tempostorm/Sap.png",
"Scavenging Hyena" : "https://s3.amazonaws.com/tempostorm/Scavenging_Hyena.png",
"Shado-Pan Monk" : "https://s3.amazonaws.com/tempostorm/Shado-Pan_Monk.png",
"Shadow Word: Pain" : "https://s3.amazonaws.com/tempostorm/Shadow_Word:_Pain.png",
"Shiv" : "https://s3.amazonaws.com/tempostorm/Shiv.png",
"Slam" : "https://s3.amazonaws.com/tempostorm/Slam.png",
"Snake Trap" : "https://s3.amazonaws.com/tempostorm/Snake_Trap.png",
"Snipe" : "https://s3.amazonaws.com/tempostorm/Snipe.png",
"Sorcerer's Apprentice" : "https://s3.amazonaws.com/tempostorm/Sorcerer's_Apprentice.png",
"Spirit Wolf" : "https://s3.amazonaws.com/tempostorm/Spirit_Wolf.png",
"Starving Buzzard" : "https://s3.amazonaws.com/tempostorm/Starving_Buzzard.png",
"Stomp" : "https://s3.amazonaws.com/tempostorm/Stomp.png",
"Stormforged Axe" : "https://s3.amazonaws.com/tempostorm/Stormforged_Axe.png",
"Succubus" : "https://s3.amazonaws.com/tempostorm/Succubus.png",
"Sunfury Protector" : "https://s3.amazonaws.com/tempostorm/Sunfury_Protector.png",
"Unstable Ghoul" : "https://s3.amazonaws.com/tempostorm/Unstable_Ghoul.png",
"Wild Growth" : "https://s3.amazonaws.com/tempostorm/Wild_Growth.png",
"Wild Pyromancer" : "https://s3.amazonaws.com/tempostorm/Wild_Pyromancer.png",
"Windfury" : "https://s3.amazonaws.com/tempostorm/Windfury.png",
"Wrath" : "https://s3.amazonaws.com/tempostorm/Wrath.png",
"Youthful Brewmaster" : "https://s3.amazonaws.com/tempostorm/Youthful_Brewmaster.png",
"Ysera Awakens" : "https://s3.amazonaws.com/tempostorm/Ysera_Awakens.png",
"Zwick" : "https://s3.amazonaws.com/tempostorm/Zwick.png",
"Acolyte of Pain" : "https://s3.amazonaws.com/tempostorm/Acolyte_of_Pain.png",
"Alarm-o-Bot" : "https://s3.amazonaws.com/tempostorm/Alarm-o-Bot.png",
"Aldor Peacekeeper" : "https://s3.amazonaws.com/tempostorm/Aldor_Peacekeeper.png",
"Animal Companion" : "https://s3.amazonaws.com/tempostorm/Animal_Companion.png",
"Arcane Golem" : "https://s3.amazonaws.com/tempostorm/Arcane_Golem.png",
"Arcane Intellect" : "https://s3.amazonaws.com/tempostorm/Arcane_Intellect.png",
"Ben Brode" : "https://s3.amazonaws.com/tempostorm/Ben_Brode.png",
"Big Game Hunter" : "https://s3.amazonaws.com/tempostorm/Big_Game_Hunter.png",
"Blood Knight" : "https://s3.amazonaws.com/tempostorm/Blood_Knight.png",
"Bob Fitch" : "https://s3.amazonaws.com/tempostorm/Bob_Fitch.png",
"Charge" : "https://s3.amazonaws.com/tempostorm/Charge.png",
"Coldlight Oracle" : "https://s3.amazonaws.com/tempostorm/Coldlight_Oracle.png",
"Coldlight Seer" : "https://s3.amazonaws.com/tempostorm/Coldlight_Seer.png",
"Counterspell" : "https://s3.amazonaws.com/tempostorm/Counterspell.png",
"Dalaran Mage" : "https://s3.amazonaws.com/tempostorm/Dalaran_Mage.png",
"Dancing Swords" : "https://s3.amazonaws.com/tempostorm/Dancing_Swords.png",
"Dark Cultist" : "https://s3.amazonaws.com/tempostorm/Dark_Cultist.png",
"Deadly Shot" : "https://s3.amazonaws.com/tempostorm/Deadly_Shot.png",
"Deathlord" : "https://s3.amazonaws.com/tempostorm/Deathlord.png",
"Demolisher" : "https://s3.amazonaws.com/tempostorm/Demolisher.png",
"Divine Favor" : "https://s3.amazonaws.com/tempostorm/Divine_Favor.png",
"Drain Life" : "https://s3.amazonaws.com/tempostorm/Drain_Life.png",
"Duplicate" : "https://s3.amazonaws.com/tempostorm/Duplicate.png",
"Eaglehorn Bow" : "https://s3.amazonaws.com/tempostorm/Eaglehorn_Bow.png",
"Earthen Ring Farseer" : "https://s3.amazonaws.com/tempostorm/Earthen_Ring_Farseer.png",
"Edwin VanCleef" : "https://s3.amazonaws.com/tempostorm/Edwin_VanCleef.png",
"Emperor Cobra" : "https://s3.amazonaws.com/tempostorm/Emperor_Cobra.png",
"Fan of Knives" : "https://s3.amazonaws.com/tempostorm/Fan_of_Knives.png",
"Far Sight" : "https://s3.amazonaws.com/tempostorm/Far_Sight.png",
"Felguard" : "https://s3.amazonaws.com/tempostorm/Felguard.png",
"Feral Spirit" : "https://s3.amazonaws.com/tempostorm/Feral_Spirit.png",
"Flame Burst" : "https://s3.amazonaws.com/tempostorm/Flame_Burst.png",
"Flesheating Ghoul" : "https://s3.amazonaws.com/tempostorm/Flesheating_Ghoul.png",
"Frost Nova" : "https://s3.amazonaws.com/tempostorm/Frost_Nova.png",
"Frothing Berserker" : "https://s3.amazonaws.com/tempostorm/Frothing_Berserker.png",
"Harvest Golem" : "https://s3.amazonaws.com/tempostorm/Harvest_Golem.png",
"Headcrack" : "https://s3.amazonaws.com/tempostorm/Headcrack.png",
"Healing Touch" : "https://s3.amazonaws.com/tempostorm/Healing_Touch.png",
"Hex" : "https://s3.amazonaws.com/tempostorm/Hex.png",
"Hogger SMASH!" : "https://s3.amazonaws.com/tempostorm/Hogger_SMASH!.png",
"Huffer" : "https://s3.amazonaws.com/tempostorm/Huffer.png",
"Ice Barrier" : "https://s3.amazonaws.com/tempostorm/Ice_Barrier.png",
"Ice Block" : "https://s3.amazonaws.com/tempostorm/Ice_Block.png",
"Imp Master" : "https://s3.amazonaws.com/tempostorm/Imp_Master.png",
"Injured Blademaster" : "https://s3.amazonaws.com/tempostorm/Injured_Blademaster.png",
"Ironforge Rifleman" : "https://s3.amazonaws.com/tempostorm/Ironforge_Rifleman.png",
"Ironfur Grizzly" : "https://s3.amazonaws.com/tempostorm/Ironfur_Grizzly.png",
"Jungle Panther" : "https://s3.amazonaws.com/tempostorm/Jungle_Panther.png",
"Kill Command" : "https://s3.amazonaws.com/tempostorm/Kill_Command.png",
"King Mukla" : "https://s3.amazonaws.com/tempostorm/King_Mukla.png",
"Kirin Tor Mage" : "https://s3.amazonaws.com/tempostorm/Kirin_Tor_Mage.png",
"Kyle Harrison" : "https://s3.amazonaws.com/tempostorm/Kyle_Harrison.png",
"Laughing Sister" : "https://s3.amazonaws.com/tempostorm/Laughing_Sister.png",
"Lava Burst" : "https://s3.amazonaws.com/tempostorm/Lava_Burst.png",
"Legacy of the Emperor" : "https://s3.amazonaws.com/tempostorm/Legacy_of_the_Emperor.png",
"Leokk" : "https://s3.amazonaws.com/tempostorm/Leokk.png",
"Lightning Storm" : "https://s3.amazonaws.com/tempostorm/Lightning_Storm.png",
"Magma Rager" : "https://s3.amazonaws.com/tempostorm/Magma_Rager.png",
"Mana Tide Totem" : "https://s3.amazonaws.com/tempostorm/Mana_Tide_Totem.png",
"Mark of Nature" : "https://s3.amazonaws.com/tempostorm/Mark_of_Nature.png",
"Mind Control Tech" : "https://s3.amazonaws.com/tempostorm/Mind_Control_Tech.png",
"Mirror Entity" : "https://s3.amazonaws.com/tempostorm/Mirror_Entity.png",
"Misha" : "https://s3.amazonaws.com/tempostorm/Misha.png",
"Murloc Warleader" : "https://s3.amazonaws.com/tempostorm/Murloc_Warleader.png",
"Nerubian" : "https://s3.amazonaws.com/tempostorm/Nerubian.png",
"Perdition's Blade" : "https://s3.amazonaws.com/tempostorm/Perdition's_Blade.png",
"Questing Adventurer" : "https://s3.amazonaws.com/tempostorm/Questing_Adventurer.png",
"Raging Worgen" : "https://s3.amazonaws.com/tempostorm/Raging_Worgen.png",
"Raid Leader" : "https://s3.amazonaws.com/tempostorm/Raid_Leader.png",
"Razorfen Hunter" : "https://s3.amazonaws.com/tempostorm/Razorfen_Hunter.png",
"Savage Roar" : "https://s3.amazonaws.com/tempostorm/Savage_Roar.png",
"Scarlet Crusader" : "https://s3.amazonaws.com/tempostorm/Scarlet_Crusader.png",
"Sense Demons" : "https://s3.amazonaws.com/tempostorm/Sense_Demons.png",
"Shade of Naxxramas" : "https://s3.amazonaws.com/tempostorm/Shade_of_Naxxramas.png",
"Shadow Bolt" : "https://s3.amazonaws.com/tempostorm/Shadow_Bolt.png",
"Shadow Word: Death" : "https://s3.amazonaws.com/tempostorm/Shadow_Word:_Death.png",
"Shadowform" : "https://s3.amazonaws.com/tempostorm/Shadowform.png",
"Shattered Sun Cleric" : "https://s3.amazonaws.com/tempostorm/Shattered_Sun_Cleric.png",
"Shield Block" : "https://s3.amazonaws.com/tempostorm/Shield_Block.png",
"SI:7 Agent" : "https://s3.amazonaws.com/tempostorm/SI:7_Agent.png",
"Silverback Patriarch" : "https://s3.amazonaws.com/tempostorm/Silverback_Patriarch.png",
"Southsea Captain" : "https://s3.amazonaws.com/tempostorm/Southsea_Captain.png",
"Spellbender" : "https://s3.amazonaws.com/tempostorm/Spellbender.png",
"Stoneskin Gargoyle" : "https://s3.amazonaws.com/tempostorm/Stoneskin_Gargoyle.png",
"Sword of Justice" : "https://s3.amazonaws.com/tempostorm/Sword_of_Justice.png",
"Tauren Warrior" : "https://s3.amazonaws.com/tempostorm/Tauren_Warrior.png",
"Thoughtsteal" : "https://s3.amazonaws.com/tempostorm/Thoughtsteal.png",
"Thrallmar Farseer" : "https://s3.amazonaws.com/tempostorm/Thrallmar_Farseer.png",
"Tinkmaster Overspark" : "https://s3.amazonaws.com/tempostorm/Tinkmaster_Overspark.png",
"Unbound Elemental" : "https://s3.amazonaws.com/tempostorm/Unbound_Elemental.png",
"Unleash the Hounds" : "https://s3.amazonaws.com/tempostorm/Unleash_the_Hounds.png",
"Vaporize" : "https://s3.amazonaws.com/tempostorm/Vaporize.png",
"Void Terror" : "https://s3.amazonaws.com/tempostorm/Void_Terror.png",
"Warsong Commander" : "https://s3.amazonaws.com/tempostorm/Warsong_Commander.png",
"Will of Mukla" : "https://s3.amazonaws.com/tempostorm/Will_of_Mukla.png",
"Wolfrider" : "https://s3.amazonaws.com/tempostorm/Wolfrider.png",
"Ancient Brewmaster" : "https://s3.amazonaws.com/tempostorm/Ancient_Brewmaster.png",
"Ancient Mage" : "https://s3.amazonaws.com/tempostorm/Ancient_Mage.png",
"Anub'ar Ambusher" : "https://s3.amazonaws.com/tempostorm/Anub'ar_Ambusher.png",
"Arathi Weaponsmith" : "https://s3.amazonaws.com/tempostorm/Arathi_Weaponsmith.png",
"Auchenai Soulpriest" : "https://s3.amazonaws.com/tempostorm/Auchenai_Soulpriest.png",
"Baine Bloodhoof" : "https://s3.amazonaws.com/tempostorm/Baine_Bloodhoof.png",
"Baron Rivendare" : "https://s3.amazonaws.com/tempostorm/Baron_Rivendare.png",
"Bite" : "https://s3.amazonaws.com/tempostorm/Bite.png",
"Blessing of Kings" : "https://s3.amazonaws.com/tempostorm/Blessing_of_Kings.png",
"Brewmaster" : "https://s3.amazonaws.com/tempostorm/Brewmaster.png",
"Chillwind Yeti" : "https://s3.amazonaws.com/tempostorm/Chillwind_Yeti.png",
"Cone of Cold" : "https://s3.amazonaws.com/tempostorm/Cone_of_Cold.png",
"Consecration" : "https://s3.amazonaws.com/tempostorm/Consecration.png",
"Cult Master" : "https://s3.amazonaws.com/tempostorm/Cult_Master.png",
"Dark Iron Dwarf" : "https://s3.amazonaws.com/tempostorm/Dark_Iron_Dwarf.png",
"Death's Bite" : "https://s3.amazonaws.com/tempostorm/Death's_Bite.png",
"Defender of Argus" : "https://s3.amazonaws.com/tempostorm/Defender_of_Argus.png",
"Dragonling Mechanic" : "https://s3.amazonaws.com/tempostorm/Dragonling_Mechanic.png",
"Dread Corsair" : "https://s3.amazonaws.com/tempostorm/Dread_Corsair.png",
"Emerald Drake" : "https://s3.amazonaws.com/tempostorm/Emerald_Drake.png",
"Ethereal Arcanist" : "https://s3.amazonaws.com/tempostorm/Ethereal_Arcanist.png",
"Fireball" : "https://s3.amazonaws.com/tempostorm/Fireball.png",
"Gnomish Inventor" : "https://s3.amazonaws.com/tempostorm/Gnomish_Inventor.png",
"Hammer of Wrath" : "https://s3.amazonaws.com/tempostorm/Hammer_of_Wrath.png",
"Hellfire" : "https://s3.amazonaws.com/tempostorm/Hellfire.png",
"Houndmaster" : "https://s3.amazonaws.com/tempostorm/Houndmaster.png",
"I Am Murloc" : "https://s3.amazonaws.com/tempostorm/I_Am_Murloc.png",
"Jay Baxter" : "https://s3.amazonaws.com/tempostorm/Jay_Baxter.png",
"Keeper of the Grove" : "https://s3.amazonaws.com/tempostorm/Keeper_of_the_Grove.png",
"Kor'kron Elite" : "https://s3.amazonaws.com/tempostorm/Kor'kron_Elite.png",
"Leeroy Jenkins" : "https://s3.amazonaws.com/tempostorm/Leeroy_Jenkins.png",
"Lightspawn" : "https://s3.amazonaws.com/tempostorm/Lightspawn.png",
"Mass Dispel" : "https://s3.amazonaws.com/tempostorm/Mass_Dispel.png",
"Massive Gnoll" : "https://s3.amazonaws.com/tempostorm/Massive_Gnoll.png",
"Master of Disguise" : "https://s3.amazonaws.com/tempostorm/Master_of_Disguise.png",
"Mindgames" : "https://s3.amazonaws.com/tempostorm/Mindgames.png",
"Mogu'shan Warden" : "https://s3.amazonaws.com/tempostorm/Mogu'shan_Warden.png",
"Mortal Strike" : "https://s3.amazonaws.com/tempostorm/Mortal_Strike.png",
"Multi-Shot" : "https://s3.amazonaws.com/tempostorm/Multi-Shot.png",
"Oasis Snapjaw" : "https://s3.amazonaws.com/tempostorm/Oasis_Snapjaw.png",
"Ogre Magi" : "https://s3.amazonaws.com/tempostorm/Ogre_Magi.png",
"Old Murk-Eye" : "https://s3.amazonaws.com/tempostorm/Old_Murk-Eye.png",
"Pit Lord" : "https://s3.amazonaws.com/tempostorm/Pit_Lord.png",
"Poison Seeds" : "https://s3.amazonaws.com/tempostorm/Poison_Seeds.png",
"Polymorph" : "https://s3.amazonaws.com/tempostorm/Polymorph.png",
"Power of the Horde" : "https://s3.amazonaws.com/tempostorm/Power_of_the_Horde.png",
"Rogues Do It..." : "https://s3.amazonaws.com/tempostorm/Rogues_Do_It....png",
"Sen'jin Shieldmasta" : "https://s3.amazonaws.com/tempostorm/Sen'jin_Shieldmasta.png",
"Shadow Madness" : "https://s3.amazonaws.com/tempostorm/Shadow_Madness.png",
"Shadowflame" : "https://s3.amazonaws.com/tempostorm/Shadowflame.png",
"Silvermoon Guardian" : "https://s3.amazonaws.com/tempostorm/Silvermoon_Guardian.png",
"Soul of the Forest" : "https://s3.amazonaws.com/tempostorm/Soul_of_the_Forest.png",
"Spellbreaker" : "https://s3.amazonaws.com/tempostorm/Spellbreaker.png",
"Stormwind Knight" : "https://s3.amazonaws.com/tempostorm/Stormwind_Knight.png",
"Summoning Portal" : "https://s3.amazonaws.com/tempostorm/Summoning_Portal.png",
"Swipe" : "https://s3.amazonaws.com/tempostorm/Swipe.png",
"Truesilver Champion" : "https://s3.amazonaws.com/tempostorm/Truesilver_Champion.png",
"Twilight Drake" : "https://s3.amazonaws.com/tempostorm/Twilight_Drake.png",
"Violet Teacher" : "https://s3.amazonaws.com/tempostorm/Violet_Teacher.png",
"Voidcaller" : "https://s3.amazonaws.com/tempostorm/Voidcaller.png",
"Wailing Soul" : "https://s3.amazonaws.com/tempostorm/Wailing_Soul.png",
"Water Elemental" : "https://s3.amazonaws.com/tempostorm/Water_Elemental.png",
"Windspeaker" : "https://s3.amazonaws.com/tempostorm/Windspeaker.png",
"Abomination" : "https://s3.amazonaws.com/tempostorm/Abomination.png",
"Arcanite Reaper" : "https://s3.amazonaws.com/tempostorm/Arcanite_Reaper.png",
"Assassin's Blade" : "https://s3.amazonaws.com/tempostorm/Assassin's_Blade.png",
"Assassinate" : "https://s3.amazonaws.com/tempostorm/Assassinate.png",
"Azure Drake" : "https://s3.amazonaws.com/tempostorm/Azure_Drake.png",
"Bane of Doom" : "https://s3.amazonaws.com/tempostorm/Bane_of_Doom.png",
"Blessed Champion" : "https://s3.amazonaws.com/tempostorm/Blessed_Champion.png",
"Bloodlust" : "https://s3.amazonaws.com/tempostorm/Bloodlust.png",
"Booty Bay Bodyguard" : "https://s3.amazonaws.com/tempostorm/Booty_Bay_Bodyguard.png",
"Brawl" : "https://s3.amazonaws.com/tempostorm/Brawl.png",
"Captain Greenskin" : "https://s3.amazonaws.com/tempostorm/Captain_Greenskin.png",
"Darkscale Healer" : "https://s3.amazonaws.com/tempostorm/Darkscale_Healer.png",
"Devilsaur" : "https://s3.amazonaws.com/tempostorm/Devilsaur.png",
"Doomguard" : "https://s3.amazonaws.com/tempostorm/Doomguard.png",
"Doomhammer" : "https://s3.amazonaws.com/tempostorm/Doomhammer.png",
"Druid of the Claw" : "https://s3.amazonaws.com/tempostorm/Druid_of_the_Claw.png",
"Earth Elemental" : "https://s3.amazonaws.com/tempostorm/Earth_Elemental.png",
"Elite Tauren Chieftain" : "https://s3.amazonaws.com/tempostorm/Elite_Tauren_Chieftain.png",
"Explosive Shot" : "https://s3.amazonaws.com/tempostorm/Explosive_Shot.png",
"Faceless Manipulator" : "https://s3.amazonaws.com/tempostorm/Faceless_Manipulator.png",
"Fen Creeper" : "https://s3.amazonaws.com/tempostorm/Fen_Creeper.png",
"Feugen" : "https://s3.amazonaws.com/tempostorm/Feugen.png",
"Frostwolf Warlord" : "https://s3.amazonaws.com/tempostorm/Frostwolf_Warlord.png",
"Gadgetzan Auctioneer" : "https://s3.amazonaws.com/tempostorm/Gadgetzan_Auctioneer.png",
"Gurubashi Berserker" : "https://s3.amazonaws.com/tempostorm/Gurubashi_Berserker.png",
"Harrison Jones" : "https://s3.amazonaws.com/tempostorm/Harrison_Jones.png",
"Holy Nova" : "https://s3.amazonaws.com/tempostorm/Holy_Nova.png",
"Holy Wrath" : "https://s3.amazonaws.com/tempostorm/Holy_Wrath.png",
"Loatheb" : "https://s3.amazonaws.com/tempostorm/Loatheb.png",
"Nightblade" : "https://s3.amazonaws.com/tempostorm/Nightblade.png",
"Nourish" : "https://s3.amazonaws.com/tempostorm/Nourish.png",
"Silver Hand Knight" : "https://s3.amazonaws.com/tempostorm/Silver_Hand_Knight.png",
"Sludge Belcher" : "https://s3.amazonaws.com/tempostorm/Sludge_Belcher.png",
"Spectral Knight" : "https://s3.amazonaws.com/tempostorm/Spectral_Knight.png",
"Spiteful Smith" : "https://s3.amazonaws.com/tempostorm/Spiteful_Smith.png",
"Stalagg" : "https://s3.amazonaws.com/tempostorm/Stalagg.png",
"Stampeding Kodo" : "https://s3.amazonaws.com/tempostorm/Stampeding_Kodo.png",
"Starfall" : "https://s3.amazonaws.com/tempostorm/Starfall.png",
"Stormpike Commando" : "https://s3.amazonaws.com/tempostorm/Stormpike_Commando.png",
"Stranglethorn Tiger" : "https://s3.amazonaws.com/tempostorm/Stranglethorn_Tiger.png",
"Tundra Rhino" : "https://s3.amazonaws.com/tempostorm/Tundra_Rhino.png",
"Venture Co. Mercenary" : "https://s3.amazonaws.com/tempostorm/Venture_Co._Mercenary.png",
"Yong Woo" : "https://s3.amazonaws.com/tempostorm/Yong_Woo.png",
"Archmage" : "https://s3.amazonaws.com/tempostorm/Archmage.png",
"Argent Commander" : "https://s3.amazonaws.com/tempostorm/Argent_Commander.png",
"Avenging Wrath" : "https://s3.amazonaws.com/tempostorm/Avenging_Wrath.png",
"Ben Thompson" : "https://s3.amazonaws.com/tempostorm/Ben_Thompson.png",
"Blizzard" : "https://s3.amazonaws.com/tempostorm/Blizzard.png",
"Boulderfist Ogre" : "https://s3.amazonaws.com/tempostorm/Boulderfist_Ogre.png",
"Cabal Shadow Priest" : "https://s3.amazonaws.com/tempostorm/Cabal_Shadow_Priest.png",
"Cairne Bloodhoof" : "https://s3.amazonaws.com/tempostorm/Cairne_Bloodhoof.png",
"Dread Infernal" : "https://s3.amazonaws.com/tempostorm/Dread_Infernal.png",
"Eric Dodds" : "https://s3.amazonaws.com/tempostorm/Eric_Dodds.png",
"Fire Elemental" : "https://s3.amazonaws.com/tempostorm/Fire_Elemental.png",
"Force of Nature" : "https://s3.amazonaws.com/tempostorm/Force_of_Nature.png",
"Frost Elemental" : "https://s3.amazonaws.com/tempostorm/Frost_Elemental.png",
"Gelbin Mekkatorque" : "https://s3.amazonaws.com/tempostorm/Gelbin_Mekkatorque.png",
"Hogger" : "https://s3.amazonaws.com/tempostorm/Hogger.png",
"Holy Fire" : "https://s3.amazonaws.com/tempostorm/Holy_Fire.png",
"Illidan Stormrage" : "https://s3.amazonaws.com/tempostorm/Illidan_Stormrage.png",
"Infernal" : "https://s3.amazonaws.com/tempostorm/Infernal.png",
"Jason Chayes" : "https://s3.amazonaws.com/tempostorm/Jason_Chayes.png",
"Kidnapper" : "https://s3.amazonaws.com/tempostorm/Kidnapper.png",
"Lord of the Arena" : "https://s3.amazonaws.com/tempostorm/Lord_of_the_Arena.png",
"Maexxna" : "https://s3.amazonaws.com/tempostorm/Maexxna.png",
"Metamorphosis" : "https://s3.amazonaws.com/tempostorm/Metamorphosis.png",
"Mukla's Big Brother" : "https://s3.amazonaws.com/tempostorm/Mukla's_Big_Brother.png",
"Priestess of Elune" : "https://s3.amazonaws.com/tempostorm/Priestess_of_Elune.png",
"Reckless Rocketeer" : "https://s3.amazonaws.com/tempostorm/Reckless_Rocketeer.png",
"Savannah Highmane" : "https://s3.amazonaws.com/tempostorm/Savannah_Highmane.png",
"Siphon Soul" : "https://s3.amazonaws.com/tempostorm/Siphon_Soul.png",
"Starfire" : "https://s3.amazonaws.com/tempostorm/Starfire.png",
"Sunwalker" : "https://s3.amazonaws.com/tempostorm/Sunwalker.png",
"Sylvanas Windrunner" : "https://s3.amazonaws.com/tempostorm/Sylvanas_Windrunner.png",
"Temple Enforcer" : "https://s3.amazonaws.com/tempostorm/Temple_Enforcer.png",
"The Beast" : "https://s3.amazonaws.com/tempostorm/The_Beast.png",
"The Black Knight" : "https://s3.amazonaws.com/tempostorm/The_Black_Knight.png",
"Vanish" : "https://s3.amazonaws.com/tempostorm/Vanish.png",
"Windfury Harpy" : "https://s3.amazonaws.com/tempostorm/Windfury_Harpy.png",
"Ancient of Lore" : "https://s3.amazonaws.com/tempostorm/Ancient_of_Lore.png",
"Ancient of War" : "https://s3.amazonaws.com/tempostorm/Ancient_of_War.png",
"Archmage Antonidas" : "https://s3.amazonaws.com/tempostorm/Archmage_Antonidas.png",
"Baron Geddon" : "https://s3.amazonaws.com/tempostorm/Baron_Geddon.png",
"Core Hound" : "https://s3.amazonaws.com/tempostorm/Core_Hound.png",
"Flamestrike" : "https://s3.amazonaws.com/tempostorm/Flamestrike.png",
"Gladiator's Longbow" : "https://s3.amazonaws.com/tempostorm/Gladiator's_Longbow.png",
"Gorehowl" : "https://s3.amazonaws.com/tempostorm/Gorehowl.png",
"Guardian of Kings" : "https://s3.amazonaws.com/tempostorm/Guardian_of_Kings.png",
"Hamilton Chu" : "https://s3.amazonaws.com/tempostorm/Hamilton_Chu.png",
"Prophet Velen" : "https://s3.amazonaws.com/tempostorm/Prophet_Velen.png",
"Ravenholdt Assassin" : "https://s3.amazonaws.com/tempostorm/Ravenholdt_Assassin.png",
"Sprint" : "https://s3.amazonaws.com/tempostorm/Sprint.png",
"Stormwind Champion" : "https://s3.amazonaws.com/tempostorm/Stormwind_Champion.png",
"War Golem" : "https://s3.amazonaws.com/tempostorm/War_Golem.png",
"Al'Akir the Windlord" : "https://s3.amazonaws.com/tempostorm/Al'Akir_the_Windlord.png",
"Grommash Hellscream" : "https://s3.amazonaws.com/tempostorm/Grommash_Hellscream.png",
"Gruul" : "https://s3.amazonaws.com/tempostorm/Gruul.png",
"Ironbark Protector" : "https://s3.amazonaws.com/tempostorm/Ironbark_Protector.png",
"Kel'Thuzad" : "https://s3.amazonaws.com/tempostorm/Kel'Thuzad.png",
"Lay on Hands" : "https://s3.amazonaws.com/tempostorm/Lay_on_Hands.png",
"Ragnaros the Firelord" : "https://s3.amazonaws.com/tempostorm/Ragnaros_the_Firelord.png",
"Ragnaros": "https://s3.amazonaws.com/tempostorm/Ragnaros_the_Firelord.png",
"Tirion Fordring" : "https://s3.amazonaws.com/tempostorm/Tirion_Fordring.png",
"Twisting Nether" : "https://s3.amazonaws.com/tempostorm/Twisting_Nether.png",
"Alexstrasza" : "https://s3.amazonaws.com/tempostorm/Alexstrasza.png",
"Cenarius" : "https://s3.amazonaws.com/tempostorm/Cenarius.png",
"King Krush" : "https://s3.amazonaws.com/tempostorm/King_Krush.png",
"Lord Jaraxxus" : "https://s3.amazonaws.com/tempostorm/Lord_Jaraxxus.png",
"Malygos" : "https://s3.amazonaws.com/tempostorm/Malygos.png",
"Nozdormu" : "https://s3.amazonaws.com/tempostorm/Nozdormu.png",
"Onyxia" : "https://s3.amazonaws.com/tempostorm/Onyxia.png",
"Placeholder Card" : "https://s3.amazonaws.com/tempostorm/Placeholder_Card.png",
"Rob Pardo" : "https://s3.amazonaws.com/tempostorm/Rob_Pardo.png",
"Ysera" : "https://s3.amazonaws.com/tempostorm/Ysera.png",
"Brian Schwab" : "https://s3.amazonaws.com/tempostorm/Brian_Schwab.png",
"Deathwing" : "https://s3.amazonaws.com/tempostorm/Deathwing.png",
"Mind Control" : "https://s3.amazonaws.com/tempostorm/Mind_Control.png",
"Pyroblast" : "https://s3.amazonaws.com/tempostorm/Pyroblast.png",
"Sea Giant" : "https://s3.amazonaws.com/tempostorm/Sea_Giant.png",
"Thaddius" : "https://s3.amazonaws.com/tempostorm/Thaddius.png",
"Mountain Giant" : "https://s3.amazonaws.com/tempostorm/Mountain_Giant.png",
"Molten Giant" : "https://s3.amazonaws.com/tempostorm/Molten_Giant.png"
}


$( document ).ready(function() {

$('.card-detect').each(function(index){
  var bodytext = $(this).html();
  $.each(cards, function(title,link){
    bodytext = bodytext.replace(title,'<a class="hovercard" href="#" data-card="'+ link + '">'+ title +'</a>');
  });
  $(this).html(bodytext);

});


$(".hovercard").mouseenter(function(d){
  b=document.createElement("img");
  if(d.clientY<400)
  {c=0}
  else
  {c=-400}
  $(b).css({top:d.pageY+c,left:d.pageX+20})}).hoverIntent(function(f){
    var d=$(window).height();
    if(f.clientY<400)
    {c=0}
    else
    {c=-400}
    $(b).css({position:"absolute","z-index":"10000",display:"block"});
    $(b).attr("src",$(this).data("card"));
    $("body").append(b)
  },
  function(){$(b).remove()}).mousemove(function(d){$(b).css({top:d.pageY+c,left:d.pageX+20})}).mouseleave(function(d){$(b).remove()});
});
